### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by TowelSniffer** [vitogit/lichess-tactics-generator#2]
is this project still maintained? it looks really cool but does not seem to be working

**Comment by vitogit** [comment]
Hi @TowelSniffer , thanks for the report. It should be fixed in this PR. The lichess api changed https://github.com/vitogit/lichess-tactics-generator/commit/6dca24ec775abccf4cc4524e9cf711e81db14275 and it's already deployed

**Comment by TowelSniffer** [comment]
Fantastic thank you so much
